<a href="https://colab.research.google.com/github/AdeDeepFishing/PythonLearning1/blob/main/numpy_crash_course_)).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np


#creating array

a=np.array([1,2,3])
b=np.arange(0,10,2)
c=np.linspace(0,1,5)

print(a)
print(b)
print(c)

[1 2 3]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [5]:
#indexing & slicing

arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[1:4])

10
[20 30 40]


In [6]:
#elemet-wise operations

a=np.array([1,2,3])
b=np.array([10,20,30])
print(a+b)
print(a*b)

[11 22 33]
[10 40 90]


In [7]:
#vectorized calculations
x=np.array([1,2,3,4])
squared=x**2
print(squared)

[ 1  4  9 16]


In [10]:
#aggregation fn
arr=np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.max(arr))

15
3.0
1.4142135623730951
5


In [11]:
a=np.array([1,2,3])
b=2
print(a*b)

[2 4 6]


In [13]:
#moving arr
arr=np.array([1,2,3,4,5])
windowSize=3
movingAvg=np.convolve(arr,np.ones(windowSize)/windowSize, mode="valid")
print(movingAvg)

[2. 3. 4.]


In [15]:
arr = np.array([10, 20, 30])
normalized = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print(normalized)

[0.  0.5 1. ]


In [21]:
arr = np.array([10, 12, 11, 100, 13])
mean = np.mean(arr)
std = np.std(arr)
lowerBound=mean-1.5*std
upperBound=mean+1.5*std
print(upperBound)
outliersMask = (arr < lowerBound) | (arr > upperBound)
outliers=arr[outliersMask]
print(outliers)

82.32118221576022
[100]


In [22]:
arr=np.array([-1,2,3,-5])
cleaned=arr[arr>=0]
print(cleaned)

[2 3]


In [26]:
arr=np.arange(0,256)
normalized= (arr-np.min(arr))/(np.max(arr)-np.min(arr))
print(normalized)


[0.         0.00392157 0.00784314 0.01176471 0.01568627 0.01960784
 0.02352941 0.02745098 0.03137255 0.03529412 0.03921569 0.04313725
 0.04705882 0.05098039 0.05490196 0.05882353 0.0627451  0.06666667
 0.07058824 0.0745098  0.07843137 0.08235294 0.08627451 0.09019608
 0.09411765 0.09803922 0.10196078 0.10588235 0.10980392 0.11372549
 0.11764706 0.12156863 0.1254902  0.12941176 0.13333333 0.1372549
 0.14117647 0.14509804 0.14901961 0.15294118 0.15686275 0.16078431
 0.16470588 0.16862745 0.17254902 0.17647059 0.18039216 0.18431373
 0.18823529 0.19215686 0.19607843 0.2        0.20392157 0.20784314
 0.21176471 0.21568627 0.21960784 0.22352941 0.22745098 0.23137255
 0.23529412 0.23921569 0.24313725 0.24705882 0.25098039 0.25490196
 0.25882353 0.2627451  0.26666667 0.27058824 0.2745098  0.27843137
 0.28235294 0.28627451 0.29019608 0.29411765 0.29803922 0.30196078
 0.30588235 0.30980392 0.31372549 0.31764706 0.32156863 0.3254902
 0.32941176 0.33333333 0.3372549  0.34117647 0.34509804 0.349019

In [5]:
arr=np.full((5,5),1)
arr[1:-1,1:-1]=0
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
